### ISSUE TITLE
Invalid redirect uri

### ISSUE THREAD

**Issue by wickercar** [Darren-project/obsidian-spotify#2]
I'm getting this error, i believe the correct redirect URI needs to be allowlisted in the app you create on the developer portal before the auth can work

**Comment by wickercar** [comment]
So I allowlisted obsidian://spotify/auth and was brought past the error screen to the permissions screen, but after I hit agree the deeplink doesn't work to authenticate me

**Comment by wickercar** [comment]
Looks like the redirect url is actually working, there's just no confirmation on the UI.

Redirect URL still needs to be allowlisted on spotify developer portal

**Comment by wickercar** [comment]
Created this PR to add this to the instructions: https://github.com/Darren-project/obsidian-spotify/pull/3

**Comment by darrenwjlau** [comment]
Pr merged

**Comment by darrenwjlau** [comment]
@wickercar thanks for that heads up
