### ISSUE TITLE
item is null on player.getPlaybackState() when currently_playing_type is "episode"

### ISSUE THREAD

**Issue by ghost** [Darren-project/obsidian-spotify#5]
I'm trying to execute this on console:

```js
const searchResults = await window.spotifysdk.player.getPlaybackState();
console.log(searchResults);
```

But the `item` property on the returning object is `null` when I am listening to a podcast (`currently_playing_type == "episode"`). When I am listening to a song, it works just fine. Can the information about podcasts be added?

**Comment by darrenwjlau** [comment]
Its raw spotify sdk not me who controls it
here's some example anyway
sorry for not replying due to school

```js
data = await spotifysdk.player.getPlaybackState("ES","track,episode")
if(data.currently_playing_type == "episode"){
        songname.innerText = "Currently playing " + data.item.name + " from " + data.item.show.name + " by " + data.item.show.publisher
        window.spotify.media.currentchangingsliders = false
        image[0].src = data.item.images[1].url
        
    } else {
        songname.innerText = "Currently playing " + data.item.name + " from " + data.item.album.name + " by " + artistname.slice(0, -2)
        window.spotify.media.currentchangingsliders = false
        image[0].src = data.item.album.images[1].url
    }
```

**Comment by darrenwjlau** [comment]
also [here's](https://developer.spotify.com/documentation/web-api) the spotify sdk docs
tell me when you have received this message and understood it

**Comment by darrenwjlau** [comment]
@turing-ex-machina

**Comment by ghost** [comment]
Sorry, I'm no longer using this plugin. I'm now using the Spotify Link plugin, which is working better for my use case. Gonna close the issue. Thanks for the support!
